links:
  rails_tutorial:
    home_page: http://www.railstutorial.org/
    help_page: http://www.railstutorial.org/help
    help_book: http://www.railstutorial.org/book
    contact: https://www.railstutorial.org/contact    
    news: https://news.learnenough.com
    author: https://www.michaelhartl.com
    screencast: https://www.learnenough.com/courses
    ruby_on_rails: https://rubyonrails.org/
  gravatar: 
    secure: https://secure.gravatar.com/avatar/
    emails: http://gravatar.com/emails

validations:
  name:
    max_length: 50
  email:
    max_length: 225
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  password:
    min_length: 6

collections:
  session_controller_create: 1
  gravatar:  
    size:
      default: 80
      list: 50
  users_default_page: 10
  psword_reset_expired_time_in_hours: 2
